// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SimpleRPC(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	Ser_StreamingRPC(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_Ser_StreamingRPCClient, error)
	Cli_StreamingRPC(ctx context.Context, opts ...grpc.CallOption) (Greeter_Cli_StreamingRPCClient, error)
	Bidirectional_StreamingRPC(ctx context.Context, opts ...grpc.CallOption) (Greeter_Bidirectional_StreamingRPCClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SimpleRPC(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SimpleRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Ser_StreamingRPC(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_Ser_StreamingRPCClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/helloworld.Greeter/Ser_StreamingRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSer_StreamingRPCClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_Ser_StreamingRPCClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSer_StreamingRPCClient struct {
	grpc.ClientStream
}

func (x *greeterSer_StreamingRPCClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) Cli_StreamingRPC(ctx context.Context, opts ...grpc.CallOption) (Greeter_Cli_StreamingRPCClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/helloworld.Greeter/Cli_StreamingRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterCli_StreamingRPCClient{stream}
	return x, nil
}

type Greeter_Cli_StreamingRPCClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterCli_StreamingRPCClient struct {
	grpc.ClientStream
}

func (x *greeterCli_StreamingRPCClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterCli_StreamingRPCClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) Bidirectional_StreamingRPC(ctx context.Context, opts ...grpc.CallOption) (Greeter_Bidirectional_StreamingRPCClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/helloworld.Greeter/Bidirectional_StreamingRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterBidirectional_StreamingRPCClient{stream}
	return x, nil
}

type Greeter_Bidirectional_StreamingRPCClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterBidirectional_StreamingRPCClient struct {
	grpc.ClientStream
}

func (x *greeterBidirectional_StreamingRPCClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterBidirectional_StreamingRPCClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting
	SimpleRPC(context.Context, *HelloRequest) (*HelloReply, error)
	Ser_StreamingRPC(*HelloRequest, Greeter_Ser_StreamingRPCServer) error
	Cli_StreamingRPC(Greeter_Cli_StreamingRPCServer) error
	Bidirectional_StreamingRPC(Greeter_Bidirectional_StreamingRPCServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SimpleRPC(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleRPC not implemented")
}
func (UnimplementedGreeterServer) Ser_StreamingRPC(*HelloRequest, Greeter_Ser_StreamingRPCServer) error {
	return status.Errorf(codes.Unimplemented, "method Ser_StreamingRPC not implemented")
}
func (UnimplementedGreeterServer) Cli_StreamingRPC(Greeter_Cli_StreamingRPCServer) error {
	return status.Errorf(codes.Unimplemented, "method Cli_StreamingRPC not implemented")
}
func (UnimplementedGreeterServer) Bidirectional_StreamingRPC(Greeter_Bidirectional_StreamingRPCServer) error {
	return status.Errorf(codes.Unimplemented, "method Bidirectional_StreamingRPC not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SimpleRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SimpleRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SimpleRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SimpleRPC(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Ser_StreamingRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).Ser_StreamingRPC(m, &greeterSer_StreamingRPCServer{stream})
}

type Greeter_Ser_StreamingRPCServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSer_StreamingRPCServer struct {
	grpc.ServerStream
}

func (x *greeterSer_StreamingRPCServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_Cli_StreamingRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).Cli_StreamingRPC(&greeterCli_StreamingRPCServer{stream})
}

type Greeter_Cli_StreamingRPCServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterCli_StreamingRPCServer struct {
	grpc.ServerStream
}

func (x *greeterCli_StreamingRPCServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterCli_StreamingRPCServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_Bidirectional_StreamingRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).Bidirectional_StreamingRPC(&greeterBidirectional_StreamingRPCServer{stream})
}

type Greeter_Bidirectional_StreamingRPCServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterBidirectional_StreamingRPCServer struct {
	grpc.ServerStream
}

func (x *greeterBidirectional_StreamingRPCServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterBidirectional_StreamingRPCServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimpleRPC",
			Handler:    _Greeter_SimpleRPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ser_StreamingRPC",
			Handler:       _Greeter_Ser_StreamingRPC_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Cli_StreamingRPC",
			Handler:       _Greeter_Cli_StreamingRPC_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Bidirectional_StreamingRPC",
			Handler:       _Greeter_Bidirectional_StreamingRPC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld/helloworld.proto",
}
